-- RUN THIS SCRIPT TO CREATE THE DB AND TABLES FOR THE API

CREATE DATABASE dice_game;

USE dice_game;

CREATE TABLE player (
    id_player INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(40) DEFAULT 'ANONYMOUS' NOT NULL UNIQUE,
    sign_up_date TIMESTAMP NOT NULL
);

CREATE TABLE game (
    id_game INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    result ENUM('WIN', 'LOSE') NOT NULL,
    dice_one INT NOT NULL UNSIGNED,
    dice_two INT NOT NULL UNSIGNED,
    player_id INT UNSIGNED,
    FOREIGN KEY (player_id) REFERENCES player(id_player)
);

